import { motion } from "framer-motion";
import { 
  BarChart3, 
  Scale, 
  Map, 
  TestTube2, 
  AlertTriangle, 
  ShieldAlert, 
  FileText,
  ArrowRight,
  Database,
  Cpu,
  Layers,
  Activity,
  Globe2
} from "lucide-react";
import { Card } from "../components/ui";

const MODULES = [
  {
    id: "live",
    title: "Live Intelligence",
    icon: <BarChart3 className="text-blue-500" size={24} />,
    color: "bg-blue-500/10 border-blue-500/20",
    desc: "Real-time aggregation of AQI, meteorological data, and satellite thermal anomalies.",
    features: ["Open-Meteo Integration", "NASA FIRMS Fire Data", "Traffic Congestion Mapping"]
  },
  {
    id: "causal",
    title: "Causal Prosecutor",
    icon: <Scale className="text-purple-500" size={24} />,
    color: "bg-purple-500/10 border-purple-500/20",
    desc: "Deterministic AI using Microsoft DoWhy to pinpoint exact pollution culprits.",
    features: ["Counterfactual Inference", "Directed Acyclic Graphs (DAGs)", "Automated Legal Briefs"]
  },
  {
    id: "ward",
    title: "Ward Intelligence",
    icon: <Map className="text-emerald-500" size={24} />,
    color: "bg-emerald-500/10 border-emerald-500/20",
    desc: "Hyper-local risk profiling for vulnerable populations across city wards.",
    features: ["Vulnerability Scoring", "Hospital/School Mapping", "Micro-targeted Priorities"]
  },
  {
    id: "simulator",
    title: "Policy Simulator",
    icon: <TestTube2 className="text-amber-500" size={24} />,
    color: "bg-amber-500/10 border-amber-500/20",
    desc: "A sandbox environment to test interventions before real-world deployment.",
    features: ["Adjustable Policy Levers", "Health & Economic Cost Estimates", "Instant Counterfactuals"]
  },
  {
    id: "interventions",
    title: "Interventions",
    icon: <ShieldAlert className="text-red-500" size={24} />,
    color: "bg-red-500/10 border-red-500/20",
    desc: "AI-recommended actionable steps based on causal inference and ward data.",
    features: ["Cost-Benefit Analysis", "Legal & Municipal Citations", "Prioritization Engine"]
  },
  {
    id: "alerts",
    title: "Alerts & Advisories",
    icon: <AlertTriangle className="text-orange-500" size={24} />,
    color: "bg-orange-500/10 border-orange-500/20",
    desc: "Real-time orchestration of public health warnings and automated responses.",
    features: ["Critical Incident Detection", "Public Advisory Broadcasting", "Actionable Feeds"]
  },
  {
    id: "reports",
    title: "Intelligence Reports",
    icon: <FileText className="text-indigo-500" size={24} />,
    color: "bg-indigo-500/10 border-indigo-500/20",
    desc: "Automated executive summaries generated by AI for city administrators.",
    features: ["PDF/JSON Exports", "LLM-powered Summaries", "Historical Audit Trails"]
  }
];

export function ProductDiscovery({ onOpenModule }: { onOpenModule: (id: string) => void }) {
  return (
    <div className="flex flex-col gap-10 max-w-7xl mx-auto pb-12">
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-center mt-6 mb-4"
      >
        <h2 className="font-display text-4xl font-extrabold text-text-primary tracking-tight">
          Explore <span className="gradient-text">VayuProsecutor</span>
        </h2>
        <p className="text-base text-text-secondary mt-2 max-w-2xl mx-auto">
          An end-to-end causal AI platform for Smart City Air Quality Management. Discover how real-time data transforms into actionable civic intelligence.
        </p>
      </motion.div>

      {/* ── ARCHITECTURE OVERVIEW PIPELINE ────────────────── */}
      <motion.div 
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ delay: 0.1, duration: 0.5 }}
        className="w-full bg-white rounded-3xl border border-border shadow-card p-8 overflow-hidden relative"
      >
        <div className="absolute top-0 right-0 p-32 bg-primary/5 rounded-full blur-[100px] pointer-events-none" />
        
        <h3 className="text-sm font-bold text-text-muted uppercase tracking-wider mb-8 flex items-center gap-2">
          <Layers size={16} /> Data Flow Architecture
        </h3>

        <div className="flex flex-col lg:flex-row items-center justify-between gap-4 lg:gap-2 relative z-10">
          <PipelineNode icon={<Database size={20} />} label="Live Data" sub="IoT, Satellite, Traffic" color="text-blue-600" bg="bg-blue-50 border-blue-200" delay={0.2} />
          <PipelineArrow delay={0.3} />
          <PipelineNode icon={<Cpu size={20} />} label="Causal Engine" sub="DoWhy Inference" color="text-purple-600" bg="bg-purple-50 border-purple-200" delay={0.4} />
          <PipelineArrow delay={0.5} />
          <PipelineNode icon={<Globe2 size={20} />} label="Ward Intel" sub="Risk Profiling" color="text-emerald-600" bg="bg-emerald-50 border-emerald-200" delay={0.6} />
          <PipelineArrow delay={0.7} />
          <PipelineNode icon={<Activity size={20} />} label="Simulations" sub="Counterfactuals" color="text-amber-600" bg="bg-amber-50 border-amber-200" delay={0.8} />
          <PipelineArrow delay={0.9} />
          <PipelineNode icon={<FileText size={20} />} label="Actionable Reports" sub="Export & Broadcast" color="text-indigo-600" bg="bg-indigo-50 border-indigo-200" delay={1.0} />
        </div>
      </motion.div>

      {/* ── MODULE CARDS ──────────────────────────────────── */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
        {MODULES.map((mod, index) => (
          <motion.div
            key={mod.id}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 + index * 0.05 }}
            className="flex"
          >
            <Card className="flex flex-col h-full overflow-hidden group hover:shadow-card-xl transition-all duration-300 p-0 border-border/60 hover:border-border">
              <div className={`h-2 w-full ${mod.color.split(' ')[0]} opacity-50`} />
              <div className="p-6 flex flex-col flex-1">
                <div className="flex items-center gap-3 mb-4">
                  <div className={`p-2.5 rounded-xl border ${mod.color}`}>
                    {mod.icon}
                  </div>
                  <h3 className="font-bold text-text-primary text-lg leading-tight">{mod.title}</h3>
                </div>
                
                <p className="text-sm text-text-secondary leading-relaxed mb-6 flex-1">
                  {mod.desc}
                </p>

                <div className="space-y-2 mb-6">
                  {mod.features.map((feat, i) => (
                    <div key={i} className="flex items-start gap-2 text-xs text-text-muted">
                      <div className="mt-1 w-1 h-1 rounded-full bg-text-muted/40 shrink-0" />
                      <span>{feat}</span>
                    </div>
                  ))}
                </div>

                <button 
                  onClick={() => onOpenModule(mod.id)}
                  className="w-full py-2.5 rounded-xl bg-bg-muted hover:bg-primary hover:text-white text-text-secondary font-bold text-sm transition-all flex items-center justify-center gap-2 group-hover:bg-primary group-hover:text-white border border-border group-hover:border-primary"
                >
                  Open Module <ArrowRight size={14} className="group-hover:translate-x-1 transition-transform" />
                </button>
              </div>
            </Card>
          </motion.div>
        ))}
      </div>
    </div>
  );
}

function PipelineNode({ icon, label, sub, color, bg, delay }: any) {
  return (
    <motion.div 
      initial={{ opacity: 0, scale: 0.8 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{ delay, duration: 0.4 }}
      className={`flex flex-col items-center justify-center p-4 rounded-2xl border ${bg} min-w-[140px] text-center shadow-sm relative`}
    >
      <div className={`mb-2 p-2 bg-white rounded-lg shadow-sm border border-black/5 ${color}`}>
        {icon}
      </div>
      <span className="font-bold text-sm text-text-primary leading-tight">{label}</span>
      <span className="text-[10px] font-medium text-text-secondary mt-1 tracking-wide">{sub}</span>
    </motion.div>
  );
}

function PipelineArrow({ delay }: { delay: number }) {
  return (
    <motion.div 
      initial={{ opacity: 0, width: 0 }}
      animate={{ opacity: 1, width: 'auto' }}
      transition={{ delay, duration: 0.4 }}
      className="hidden lg:flex flex-1 h-px bg-border items-center justify-center min-w-[30px]"
    >
      <div className="w-full relative flex items-center justify-center">
        <ArrowRight size={14} className="text-border absolute bg-white" />
      </div>
    </motion.div>
  );
}
